"""initial schema

Revision ID: 1f34d7395ed8
Revises: 
Create Date: 2026-07-31 03:04:16.569839
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '1f34d7395ed8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sa.Enum('manual', 'email', 'system', name='actor'), nullable=False),
    sa.Column('before_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('email_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imap_uid', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('looks_like_travel', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_message_imap_uid'), ['imap_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_message_looks_like_travel'), ['looks_like_travel'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_message_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_message_received_at'), ['received_at'], unique=False)

    op.create_table('passkey_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passkey_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkey_credential_credential_id'), ['credential_id'], unique=True)

    op.create_table('passport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.Enum('MX', 'US', name='nationality'), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number_last4', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passport_expires_on'), ['expires_on'], unique=False)

    op.create_table('recovery_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_code_code_hash'), ['code_hash'], unique=True)

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_token_hash'), ['token_hash'], unique=True)

    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_start_date'), ['start_date'], unique=False)

    op.create_table('country_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('entered_on', sa.Date(), nullable=False),
    sa.Column('exited_on', sa.Date(), nullable=True),
    sa.Column('port_of_entry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permit_type', sa.Enum('visa_free', 'evisa', 'visa_on_arrival', 'visa', 'residency', 'citizen', name='permittype'), nullable=True),
    sa.Column('permitted_days', sa.Integer(), nullable=True),
    sa.Column('must_exit_by', sa.Date(), nullable=True),
    sa.Column('stamp_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['passport.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_entry_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_entry_entered_on'), ['entered_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_entry_must_exit_by'), ['must_exit_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_entry_passport_id'), ['passport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_entry_trip_id'), ['trip_id'], unique=False)

    op.create_table('extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='extractionstatus'), nullable=False),
    sa.Column('suggested_trip_id', sa.Integer(), nullable=True),
    sa.Column('applied_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_trip_id'], ['trip.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_email_message_id'), ['email_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_status'), ['status'], unique=False)

    op.create_table('leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('flight', 'train', 'bus', 'ferry', 'car', name='travelmode'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'internal', 'outbound', name='legdirection'), nullable=False),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_place', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_iata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depart_at', sa.DateTime(), nullable=True),
    sa.Column('to_place', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_iata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arrive_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leg_arrive_at'), ['arrive_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leg_depart_at'), ['depart_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leg_trip_id'), ['trip_id'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('appointment', 'reminder', 'expense', 'idea', 'general', name='notecategory'), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_on_date'), ['on_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_remind_at'), ['remind_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_trip_id'), ['trip_id'], unique=False)

    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('entry_card', 'visa', 'eta', 'insurance', 'vaccination', 'onward_ticket', 'custom', name='requirementkind'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'submitted', 'approved', 'not_required', name='requirementstatus'), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_trip_id'), ['trip_id'], unique=False)

    op.create_table('stay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('hotel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stay_check_in'), ['check_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_stay_check_out'), ['check_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_stay_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stay_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stay_trip_id'))
        batch_op.drop_index(batch_op.f('ix_stay_country_code'))
        batch_op.drop_index(batch_op.f('ix_stay_check_out'))
        batch_op.drop_index(batch_op.f('ix_stay_check_in'))

    op.drop_table('stay')
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_trip_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_status'))
        batch_op.drop_index(batch_op.f('ix_requirement_due_date'))

    op.drop_table('requirement')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_trip_id'))
        batch_op.drop_index(batch_op.f('ix_note_remind_at'))
        batch_op.drop_index(batch_op.f('ix_note_on_date'))
        batch_op.drop_index(batch_op.f('ix_note_done'))
        batch_op.drop_index(batch_op.f('ix_note_category'))

    op.drop_table('note')
    with op.batch_alter_table('leg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leg_trip_id'))
        batch_op.drop_index(batch_op.f('ix_leg_depart_at'))
        batch_op.drop_index(batch_op.f('ix_leg_arrive_at'))

    op.drop_table('leg')
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_status'))
        batch_op.drop_index(batch_op.f('ix_extraction_email_message_id'))

    op.drop_table('extraction')
    with op.batch_alter_table('country_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_entry_trip_id'))
        batch_op.drop_index(batch_op.f('ix_country_entry_passport_id'))
        batch_op.drop_index(batch_op.f('ix_country_entry_must_exit_by'))
        batch_op.drop_index(batch_op.f('ix_country_entry_entered_on'))
        batch_op.drop_index(batch_op.f('ix_country_entry_country_code'))

    op.drop_table('country_entry')
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_start_date'))
        batch_op.drop_index(batch_op.f('ix_trip_end_date'))
        batch_op.drop_index(batch_op.f('ix_trip_archived'))

    op.drop_table('trip')
    op.drop_table('setting')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_session_expires_at'))

    op.drop_table('session')
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_code_code_hash'))

    op.drop_table('recovery_code')
    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passport_expires_on'))

    op.drop_table('passport')
    with op.batch_alter_table('passkey_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkey_credential_credential_id'))

    op.drop_table('passkey_credential')
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_message_received_at'))
        batch_op.drop_index(batch_op.f('ix_email_message_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_message_looks_like_travel'))
        batch_op.drop_index(batch_op.f('ix_email_message_imap_uid'))

    op.drop_table('email_message')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
