"""requirement discrepancy_nationality: loud passport-mismatch flag

Revision ID: 50cd760e587a
Revises: f086d52834fb
Create Date: 2026-08-04 12:01:11.741552
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '50cd760e587a'
down_revision: Union[str, None] = 'f086d52834fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discrepancy_nationality', sa.Enum('MX', 'US', name='nationality'), nullable=True))
        batch_op.create_index(batch_op.f('ix_requirement_discrepancy_nationality'), ['discrepancy_nationality'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_discrepancy_nationality'))
        batch_op.drop_column('discrepancy_nationality')

    # ### end Alembic commands ###
