"""immigration readiness: entry_policy, requirement source, email immigration flag

Revision ID: b119ab960928
Revises: 3f166b5b4e6d
Create Date: 2026-08-04 10:26:48.066636
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'b119ab960928'
down_revision: Union[str, None] = '3f166b5b4e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('nationality', sa.Enum('MX', 'US', name='nationality'), nullable=False),
    sa.Column('permit_type', sa.Enum('visa_free', 'evisa', 'visa_on_arrival', 'visa', 'residency', 'citizen', name='permittype'), nullable=True),
    sa.Column('permitted_days', sa.Integer(), nullable=True),
    sa.Column('visa_required', sa.Boolean(), nullable=False),
    sa.Column('entry_card_required', sa.Boolean(), nullable=False),
    sa.Column('entry_card_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eta_required', sa.Boolean(), nullable=False),
    sa.Column('insurance_required', sa.Boolean(), nullable=False),
    sa.Column('vaccination_required', sa.Boolean(), nullable=False),
    sa.Column('onward_ticket_required', sa.Boolean(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('advisory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'nationality', name='uq_entry_policy_country_nationality')
    )
    with op.batch_alter_table('entry_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_policy_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_policy_nationality'), ['nationality'], unique=False)

    with op.batch_alter_table('email_message', schema=None) as batch_op:
        # server_default is required: SQLite refuses to add a NOT NULL column to
        # a table that already has rows unless it knows what to put in them.
        batch_op.add_column(sa.Column(
            'looks_like_immigration', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ))
        batch_op.create_index(batch_op.f('ix_email_message_looks_like_immigration'), ['looks_like_immigration'], unique=False)

    with op.batch_alter_table('requirement', schema=None) as batch_op:
        # Every row created before this column existed was typed by hand.
        batch_op.add_column(sa.Column(
            'source', sa.Enum('manual', 'email', 'system', name='actor'),
            nullable=False, server_default='manual',
        ))
        batch_op.create_index(batch_op.f('ix_requirement_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_source'))
        batch_op.drop_column('source')

    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_message_looks_like_immigration'))
        batch_op.drop_column('looks_like_immigration')

    with op.batch_alter_table('entry_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_policy_nationality'))
        batch_op.drop_index(batch_op.f('ix_entry_policy_country_code'))

    op.drop_table('entry_policy')
    # ### end Alembic commands ###
