"""drop trip title archived and leg direction

Revision ID: ba5dfa0e58f9
Revises: c0d08c15146c
Create Date: 2026-07-31 10:26:11.276611
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'ba5dfa0e58f9'
down_revision: Union[str, None] = 'c0d08c15146c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leg', schema=None) as batch_op:
        batch_op.drop_column('direction')

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_archived')
        batch_op.drop_column('title')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.create_index('ix_trip_archived', ['archived'], unique=False)

    with op.batch_alter_table('leg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.VARCHAR(length=8), nullable=False))

    # ### end Alembic commands ###
