"""leg country_code

Revision ID: c0d08c15146c
Revises: 1f34d7395ed8
Create Date: 2026-07-31 09:41:55.416003
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'c0d08c15146c'
down_revision: Union[str, None] = '1f34d7395ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("leg", schema=None) as batch_op:
        # server_default is required: SQLite refuses to add a NOT NULL column to
        # a table that already has rows unless it knows what to put in them.
        batch_op.add_column(
            sa.Column(
                "country_code",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_leg_country_code"), ["country_code"], unique=False
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leg_country_code'))
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
