"""extraction kind: booking vs immigration confirmation

Revision ID: f086d52834fb
Revises: b119ab960928
Create Date: 2026-08-04 11:31:59.770273
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'f086d52834fb'
down_revision: Union[str, None] = 'b119ab960928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        # server_default is required: SQLite refuses to add a NOT NULL column
        # to a table that already has rows unless it knows what to put in
        # them. Every row before this column existed was a booking -- the
        # only kind that existed then (autogenerate misses this; hand-added,
        # same trap as b119ab960928 and c0d08c15146c before it).
        batch_op.add_column(sa.Column(
            'kind', sa.Enum('booking', 'immigration', name='extractionkind'),
            nullable=False, server_default='booking',
        ))
        batch_op.create_index(batch_op.f('ix_extraction_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_kind'))
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
